# Generated by Django 4.2.1 on 2024-08-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('norma', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('criterioEvaluacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaIncio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tipoOferta', models.CharField(choices=[('Oferta Abierta', 'Oferta Abierta'), ('Colegio', 'Colegio'), ('Empresa', 'Empresa'), ('Institución', 'Institución'), ('Programa Especial', 'Programa Especial'), ('Educación Continua', 'Educación Continua')], default='Oferta Abierta', max_length=100)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('A Distancia', 'A Distancia'), ('Mixta (B-Learning)', 'Mixta (B-Learning)'), ('Contrato de Aprendizaje', 'Contrato de Aprendizaje'), ('Articulación con la Media', 'Articulación con la Media'), ('Escuela-Taller', 'Escuela-Taller')], default='Presencial', max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=15)),
                ('version', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('duracionLectiva', models.IntegerField()),
                ('duracionProductiva', models.IntegerField()),
                ('duracionTotal', models.IntegerField()),
                ('tipoPrograma', models.CharField(choices=[('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Especialización Técnica', 'Especialización Técnica'), ('Especialización Tecnológica', 'Especialización Tecnológica'), ('Curso Corto', 'Curso Corto'), ('Formación Continua', 'Formación Continua'), ('Capacitación a Medida', 'Capacitación a Medida'), ('Curso Virtual', 'Curso Virtual'), ('Curso de Idiomas', 'Curso de Idiomas'), ('Emprendimiento', 'Emprendimiento')], default='Técnico', max_length=100)),
                ('certificacion', models.CharField(choices=[('Certificado Técnico', 'Certificado Técnico'), ('Certificado Tecnólogo', 'Certificado Tecnólogo'), ('Certificado de Especialización Técnica', 'Certificado de Especialización Técnica'), ('Certificado de Especialización Tecnológica', 'Certificado de Especialización Tecnológica'), ('Certificado de Curso Corto', 'Certificado de Curso Corto'), ('Certificado de Formación Continua', 'Certificado de Formación Continua'), ('Certificado de Capacitación a Medida', 'Certificado de Capacitación a Medida'), ('Certificado de Curso Virtual', 'Certificado de Curso Virtual'), ('Certificado de Idiomas', 'Certificado de Idiomas'), ('Certificado de Emprendimiento', 'Certificado de Emprendimiento')], default='Certificado Técnico', max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadanía'), ('CE', 'Cedula de Extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'Número de identificación tributaria')], default='CC', max_length=3)),
                ('documento', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=7, null=True)),
                ('celular', models.CharField(max_length=10)),
                ('rol', models.CharField(choices=[('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz'), ('Administrador', 'Administrador')], default='Aprendiz', max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('titulacion', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Trimestre 4', 'Trimestre 4'), ('Trimestre 5', 'Trimestre 5'), ('Trimestre 6', 'Trimestre 6'), ('Trimestre 7', 'Trimestre 7'), ('Trimestre 8', 'Trimestre 8')], default='Trimestre 1', max_length=15)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(choices=[('Rap. 1', 'Rap. 1'), ('Rap. 2', 'Rap. 2'), ('Rap. 3', 'Rap. 3'), ('Rap. 4', 'Rap. 4'), ('Rap. 5', 'Rap. 5'), ('Rap. 6', 'Rap. 6'), ('Rap. 7', 'Rap. 7'), ('Rap. 8', 'Rap. 8'), ('Rap. 9', 'Rap. 9'), ('Rap. 10', 'Rap. 10'), ('Rap. 11', 'Rap. 11'), ('Rap. 12', 'Rap. 12'), ('Rap. 13', 'Rap. 13'), ('Rap. 14', 'Rap. 14'), ('Rap. 15', 'Rap. 15')], default='Rap. 1', max_length=15)),
                ('descripcion', models.TextField()),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneacionPedagogica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.IntegerField()),
                ('competencia', models.IntegerField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='Lunes', max_length=15)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aula')),
                ('planeacionPedagogica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planeacionpedagogica')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
    ]
