# Generated by Django 4.2.1 on 2024-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuarioReceptor', models.IntegerField()),
                ('usuarioEmisor', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('comentario', models.TextField()),
            ],
        ),
    ]
