# Generated by Django 4.2.1 on 2024-08-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ficha')),
            ],
        ),
    ]
