# Generated by Django 4.2.1 on 2024-08-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_horario_aula_alter_mensaje_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='fechaIncio',
            new_name='fechaInicio',
        ),
    ]
