# Generated by Django 4.2.1 on 2024-08-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_asignacioncoordinador_inscripcionaprendiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz'), ('Coordinador', 'Coordinador')], default='Aprendiz', max_length=15, null=True),
        ),
    ]
