# Generated by Django 4.2.1 on 2024-08-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_planeacion_producto_programacion_tematica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionInstructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuarioInstructor', models.IntegerField()),
                ('usuarioCoordinador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aula')),
            ],
        ),
    ]
