# Generated by Django 4.2.1 on 2024-08-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_asignacioninstructor_asignacionaula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fechaRecibido',
            new_name='fechaLeido',
        ),
    ]
