# Generated by Django 4.2.1 on 2024-08-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_fecharecibido_mensaje_fechaleido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.BooleanField(default=False),
        ),
    ]
