# Generated by Django 4.2.1 on 2024-09-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mensaje_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='correoElectronico',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='celular',
            new_name='numeroDocumento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='documento',
            new_name='telefonoCelular',
        ),
    ]
