# Generated by Django 4.2.1 on 2024-09-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_correo_usuario_correoelectronico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='comentario',
            new_name='contenido',
        ),
    ]
