# Generated by Django 4.2.1 on 2024-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_comentario_mensaje_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz'), ('Coordinador', 'Coordinador'), ('Administrador', 'Administrador')], default='Aprendiz', max_length=15, null=True),
        ),
    ]
