# Generated by Django 4.2.1 on 2024-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
