# Generated by Django 4.2.1 on 2024-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_mensaje_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correoElectronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
