# Generated by Django 4.2.1 on 2024-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_usuario_correoelectronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='lugar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='eliminarEmisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='eliminarReceptor',
            field=models.BooleanField(default=False),
        ),
    ]
