# Generated by Django 4.2.1 on 2024-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ficha_lugar_mensaje_eliminaremisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion',
            name='diasRecomendados',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planeacion',
            name='horasRecomendadas',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='programa',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
