# Generated by Django 4.2.1 on 2024-09-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_planeacion_diasrecomendados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionaula',
            old_name='usuario',
            new_name='programa',
        ),
        migrations.RenameField(
            model_name='asignacioncoordinador',
            old_name='Programa',
            new_name='programa',
        ),
        migrations.RenameField(
            model_name='asignacioninstructor',
            old_name='usuarioCoordinador',
            new_name='programa',
        ),
        migrations.RemoveField(
            model_name='asignacioninstructor',
            name='usuarioInstructor',
        ),
        migrations.AddField(
            model_name='asignacioninstructor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoInstructor',
            field=models.CharField(blank=True, choices=[('Planta', 'Planta'), ('Contratista', 'Contratista')], default='Planta', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='LiderFicha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ficha')),
            ],
        ),
    ]
