# Generated by Django 4.2.1 on 2024-09-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_planeacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='duracionProductiva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=15),
        ),
    ]
