# Generated by Django 4.2.1 on 2024-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_duracionpresencial_planeacion_trabajoautonomo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion',
            name='creditos',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
