# Generated by Django 4.2.1 on 2024-10-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_programa_tipooferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipoOferta',
            field=models.CharField(choices=[('Oferta Abierta', 'Oferta Abierta'), ('Colegio', 'Colegio'), ('Empresa', 'Empresa'), ('Institución', 'Institución'), ('Programa Especial', 'Programa Especial'), ('Educación Continua', 'Educación Continua'), ('Cadena de Formación', 'Cadena de Formación')], default='Oferta Abierta', max_length=100),
        ),
    ]
