# Generated by Django 4.2.1 on 2024-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_programa_tipooferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='lugar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
