# Generated by Django 4.2.1 on 2024-10-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_ficha_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipoOferta',
            field=models.CharField(choices=[('Oferta', 'Oferta'), ('Cadena de Formación', 'Cadena de Formación')], default='Oferta', max_length=100),
        ),
    ]
