# Generated by Django 4.2.1 on 2024-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_programa_tipooferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='tipoOferta',
        ),
        migrations.AddField(
            model_name='ficha',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('A Distancia', 'A Distancia'), ('Mixta (B-Learning)', 'Mixta (B-Learning)'), ('Contrato de Aprendizaje', 'Contrato de Aprendizaje'), ('Articulación con la Media', 'Articulación con la Media'), ('Escuela-Taller', 'Escuela-Taller')], default='Presencial', max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tipoOferta',
            field=models.CharField(choices=[('Oferta', 'Oferta'), ('Cadena de Formación', 'Cadena de Formación')], default='Oferta', max_length=100),
        ),
    ]
